### ISSUE TITLE
To-do list for v1.0 release

### ISSUE THREAD

**Issue by chalkpe** [ChalkPE/Cameraman#1]
- [x] Delay when travelling starts
- [x] Save waypoints
- [x] Curved movements
- [x] ~~Open the GUI screen on the clients by scripts~~ **Shelved**
- [x] Translation for another languages
